feat: add a docs action
go-vela/cli pull request #191
Opened 2021-01-14 21:40 UTC by kneal

This PR adds the ability to generate documentation to live within this repository. The generation is a built-in feature of [urfave/cli](https://github.com/urfave/cli). For details on their implementation, you can see https://github.com/urfave/cli/pull/830

There is a Lorem ipsum example available that shows the implementation. 
https://github.com/jribe/cli/wiki/Markdown-doc-example

The plan will be to reference the new `DOCS.md` file in this repository directly on the Vela documentation site. This will make it so all docs on the site are sourced from the commands directly and generated then propagated to our site.

2021-01-18 15:13 UTC, kneal commented
Per feedback making the command hidden: https://github.com/go-vela/cli/pull/191/commits/71ee65b86c07fe3aeff2d3c8a6334e7c25389a16

```release/darwin/amd64/vela gn
NAME:
   vela generate - Generate resources for Vela via subcommands

USAGE:
   vela generate command [command options] [arguments...]

DESCRIPTION:
   Use this command to generate resources for Vela.

COMMANDS:
   completion  Generate a shell auto completion script
   config      Generate the config file used in the CLI
   pipeline    Generate a valid Vela pipeline
   help, h     Shows a list of commands or help for one command```

2021-01-18 15:54 UTC, davidvader commented on action/docs/generate.go
> +		man, err := a.ToMarkdown()
.toMan

2021-01-18 15:56 UTC, davidvader commented on action/docs_generate.go
> +// produce the config file.
typo?
```
// produce the config file.

```

2021-01-18 15:57 UTC, jbrockopp requested changes

2021-01-18 15:57 UTC, jbrockopp commented on DOCS.md
> +**--config, -c**="": path to Vela configuration file (default: /Users/Z001NR1/.vela/config.yml)
I believe this will need to be updated.. the default path looks inaccurate

2021-01-19 15:15 UTC, matt-fevold approved these changes
looks like all feedback was addressed. LGTM 🐕

2021-01-19 16:03 UTC, davidvader approved these changes
ty for making those updates, LGTM

2021-01-19 16:43 UTC, jbrockopp approved these changes
LGTM

2021-01-19 16:46 UTC, merged