enhance(builds): enable filtering by event, status, and branch
go-vela/cli pull request #259
Opened 2021-09-08 18:54 UTC by JordanSussman

This functionality enables the user to specify the `event`, `status`, and `branch` flags when utilizing the `vela get builds` command to further filter the list of builds returned by the API.

closes https://github.com/go-vela/community/issues/393

2021-09-08 18:54 UTC, JordanSussman commented on go.mod
> +replace github.com/go-vela/sdk-go => github.com/JordanSussman/sdk-go v0.1.2-0.20210908184645-0f26a72fa616
Will remove once https://github.com/go-vela/sdk-go/pull/120 has been merged.

2021-09-09 15:01 UTC, jbrockopp requested changes

2021-09-09 15:01 UTC, jbrockopp commented on action/build/get.go
>  	// https://pkg.go.dev/github.com/go-vela/sdk-go/vela?tab=doc#ListOptions
Could we update the link here for the new type being used?

```suggestion
	// https://pkg.go.dev/github.com/go-vela/sdk-go/vela?tab=doc#BuildListOptions
```

2021-09-09 15:08 UTC, jbrockopp approved these changes
LGTM

2021-09-10 16:14 UTC, wass3r approved these changes

2021-09-10 16:14 UTC, merged