feat(cli): adding sync repo and sync repos to CLI
go-vela/cli pull request #313
Opened 2021-11-24 16:49 UTC by ecrupper

Creating the capability to run the new API command to sync repositories between Vela and SCM in the CLI. Currently using the format: `vela sync repo --o <org> --r <repo>` and `vela sync repo --o <org> --all` for sync and syncAll respectively. Open to other ideas on that front. I figured having only one letter difference (`sync repo` and `sync repos`) is a tad worrying.

2021-11-30 21:08 UTC, KellyMerrick submitted a review, later dismissed
lgtm

2021-12-02 15:09 UTC, jbrockopp requested changes

2021-12-02 15:09 UTC, jbrockopp commented on command/repo/sync.go
> +			Action: "syncAll",
Should this be a constant that is added to `github.com/go-vela/cli/internal`?

https://github.com/go-vela/cli/blob/85ac81f95e15d40701c6ea4496a3cf5b1a3e4444/internal/internal.go#L128-L174

2021-12-02 15:09 UTC, jbrockopp commented on command/repo/sync.go
> +		Action: "sync",
Should this be a constant that is added to `github.com/go-vela/cli/internal`?

https://github.com/go-vela/cli/blob/85ac81f95e15d40701c6ea4496a3cf5b1a3e4444/internal/internal.go#L128-L174

2021-12-06 19:41 UTC, KellyMerrick submitted a review, later dismissed
lgtm

2021-12-13 15:06 UTC, jbrockopp approved these changes
LGTM

2021-12-15 21:04 UTC, jbrockopp approved these changes
LGTM

2021-12-16 21:37 UTC, KellyMerrick approved these changes
lgtm

2021-12-16 21:45 UTC, merged