feat: add support for schedules
go-vela/cli pull request #446
Opened 2023-05-05 15:48 UTC by jbrockopp

xref: https://github.com/go-vela/community/issues/538

Part of https://github.com/go-vela/community/pull/772

Dependent on https://github.com/go-vela/sdk-go/pull/233 and https://github.com/go-vela/worker/pull/479

This adds a set of `schedule` based commands to support the new `/api/v1/schedules` endpoints:

```
vela add schedule --org <org> --repo <repo> --schedule <name> --entry <entry>
vela get schedule --org <org> --repo <repo>
vela view schedule --org <org> --repo <repo> --schedule <name>
vela update schedule --org <org> --repo <repo> --schedule <name> --entry <entry>
vela remove schedule --org <org> --repo <repo> --schedule <name>
```

2023-05-31 03:19 UTC, JordanSussman approved these changes

2023-06-02 16:11 UTC, jbrockopp commented on cmd/vela-cli/view.go
> +		// add the sub command for getting a list of schedules
fixed 👍

2023-06-02 16:22 UTC, JordanSussman approved these changes

2023-06-02 16:22 UTC, JordanSussman approved these changes

2023-06-05 14:37 UTC, wass3rw3rk approved these changes

2023-06-05 14:59 UTC, JordanSussman submitted a review, later dismissed

2023-06-05 15:21 UTC, plyr4 requested changes
nice, just a couple minor tweaks

2023-06-05 15:21 UTC, plyr4 commented on action/schedule/remove_test.go
> +				t.Errorf("Remove for %s returned err: %v", err, test.name)
```suggestion
				t.Errorf("Remove for %s returned err: %v", test.name, err)
```

2023-06-05 15:21 UTC, plyr4 commented on action/schedule/update_test.go
> +				t.Errorf("Update for %s returned err: %v", err, test.name)
```suggestion
				t.Errorf("Update for %s returned err: %v", test.name, err)
```

2023-06-05 21:24 UTC, wass3rw3rk approved these changes

2023-06-05 21:25 UTC, merged