feat: adding branch field to scheduled builds
go-vela/cli pull request #472
Opened 2023-08-25 16:36 UTC by claire1618

2023-08-25 16:48 UTC, ecrupper requested changes
One tiny thing then LGTM

2023-08-25 16:48 UTC, ecrupper commented on command/schedule/update.go
> +			Aliases: []string{"e"},
```suggestion
			Aliases: []string{"b"},
```

2023-08-25 16:50 UTC, claire1618 commented on command/schedule/update.go
> +			Aliases: []string{"e"},
Changed!

2023-08-25 18:03 UTC, ecrupper approved these changes

2023-08-28 14:21 UTC, plyr4 approved these changes

2023-08-28 15:45 UTC, timhuynh94 approved these changes

2023-08-28 16:44 UTC, merged